### ISSUE TITLE
Antigate is not working on Python 2.6.6

### ISSUE THREAD

**Issue by hrushikesh198** [gotlium/antigate#15]
```
Traceback (most recent call last):
  File "captcha_utils.py", line 271, in <module>
    anti_gate_driver(2)
  File "captcha_utils.py", line 260, in anti_gate_driver
    gate = AntiGate(api_key, img)
  File "/usr/lib/python2.6/site-packages/antigate/__init__.py", line 65, in __init__
    self.run(captcha_file)
  File "/usr/lib/python2.6/site-packages/antigate/__init__.py", line 220, in run
    self.send(captcha_file)
  File "/usr/lib/python2.6/site-packages/antigate/__init__.py", line 175, in send
    return self._send(captcha_file)
  File "/usr/lib/python2.6/site-packages/antigate/__init__.py", line 157, in _send
    self._request(self._get_input_url(), 'Can not send captcha')
  File "/usr/lib/python2.6/site-packages/antigate/__init__.py", line 133, in _request
    code, response = self.http.request(url)
  File "/usr/lib/python2.6/site-packages/antigate/backends/grab_lib.py", line 17, in request
    self.grab.go(url)
  File "/usr/lib/python2.6/site-packages/grab/base.py", line 377, in go
    return self.request(url=url, **kwargs)
  File "/usr/lib/python2.6/site-packages/grab/base.py", line 443, in request
    self.prepare_request(**kwargs)
  File "/usr/lib/python2.6/site-packages/grab/base.py", line 403, in prepare_request
    self.transport.process_config(self)
  File "/usr/lib/python2.6/site-packages/grab/transport/curl.py", line 204, in process_config
    u'%s: %s' % (six.text_type(ex), grab.config['url']))
grab.error.GrabInvalidUrl: decode() takes no keyword arguments: http://antigate.com/in.php
```

**Comment by gotlium** [comment]
You can use latest version from git and urllib as http backend. Possible it will be work. On next update py2.6 will be removed from compatibility list.
