### ISSUE TITLE
Installing in virtualenv without pip error

### ISSUE THREAD

**Issue by AlesDokshanin** [gotlium/antigate#6]
Cannot install this package inside virtualenv by typing "pip install antigate" without administrator privilegies. I get the following output.
---
```
(env)unknwn $ pip install antigate
Downloading/unpacking antigate
  Downloading antigate-1.3.tar.gz
  Running setup.py (path:/home/unknwn/Dev/Python/mysite/env/build/antigate/setup.py) egg_info for package antigate
    
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking pycurl (from antigate)
  Downloading pycurl-7.19.5.1.tar.gz (142kB): 142kB downloaded
  Running setup.py (path:/home/unknwn/Dev/Python/mysite/env/build/pycurl/setup.py) egg_info for package pycurl
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/unknwn/Dev/Python/mysite/env/build/pycurl/setup.py", line 634, in <module>
        ext = get_extension(split_extension_source=split_extension_source)
      File "/home/unknwn/Dev/Python/mysite/env/build/pycurl/setup.py", line 392, in get_extension
        ext_config = ExtensionConfiguration()
      File "/home/unknwn/Dev/Python/mysite/env/build/pycurl/setup.py", line 65, in __init__
        self.configure()
      File "/home/unknwn/Dev/Python/mysite/env/build/pycurl/setup.py", line 100, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/unknwn/Dev/Python/mysite/env/build/pycurl/setup.py", line 634, in <module>

    ext = get_extension(split_extension_source=split_extension_source)

  File "/home/unknwn/Dev/Python/mysite/env/build/pycurl/setup.py", line 392, in get_extension

    ext_config = ExtensionConfiguration()

  File "/home/unknwn/Dev/Python/mysite/env/build/pycurl/setup.py", line 65, in __init__

    self.configure()

  File "/home/unknwn/Dev/Python/mysite/env/build/pycurl/setup.py", line 100, in configure_unix

    raise ConfigurationError(msg)

__main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/unknwn/Dev/Python/mysite/env/build/pycurl
Storing debug log for failure in /home/unknwn/.pip/pip.log
```

**Comment by gotlium** [comment]
libcurl not installed on your system
